app:
    name: 'burnout-platform-backend'
    version: '1.0.0'
http:
    port: 8080

log:
    level: 'debug'

postgres:
    max_pool_size: 20
    default_pg_url: 'postgres://just_pg_user:just_pg_password@postgres:5432/just_pg_database'
